name: Auto-comment-issue

on:
  issues:
    types: opened

jobs:
  add_comment:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Debug event payload 
        run: echo '${{ toJson(github.event) }}'

      - name: Add the comment
        run: |
          COMMENT_ID=$(gh issue comment $ISSUE --body "Wow, we have a new issue!" --repo $REPO)
          echo "COMMENT_ID is $COMMENT_ID"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.number }}
          REPO: ${{ github.event.repository.full_name }}

      - name: Show comment_id
        run: echo "COMMENT_ID is $COMMENT_ID"
        
