name: Auto-comment-issue

on:
  issues:
    types: opened

jobs:
  add_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Debug event payload 
        run: echo '${{ toJson(github.event) }}'
       

    
