name: Python Uppercase

on:
  push:
    paths:
      - ".github/workflows/python-uppercase.yml"
      - "py-upper/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check python version
        run: python -V

      - name: Display current directory
        run: pwd 

      - name: List files
        run: ls -R        

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files
        run: ls -R                

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Check python version
        run: python -V

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "py-upper/requirements.txt"
          update-pip: "true"

      - name: Run tests
        working-directory: py-upper
        run: pytest -v
