name: Python Uppercase

on:
  push:
    paths:
      - ".github/workflows/python_uppercase.yml"
      - "py-upper/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check python version
        run: python -V

      - name: Display current directory
        run: pwd 

      - name: List files
        run: ls -R        

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files
        run: ls -R                